### ISSUE TITLE
Can't assign requested address

### ISSUE THREAD

**Issue by ceppelli** [SajjadPourali/udp-stream#2]
Using the  UDPStream::connect method, when trying to send but to the remote peer the following exception will be thrown:

**Error: Os { code: 49, kind: AddrNotAvailable, message: "Can't assign requested address" }**

Env
- macOS Monterey
- rustc 1.68.2 (9eb3afe9e 2023-03-27)

I found the following solution which works on my Mac
lib.rs at line 187
`
// SocketAddr::new(IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1)), 0)
SocketAddr::new(IpAddr::V4(Ipv4Addr::UNSPECIFIED), 0)
`

Thanks

**Comment by SajjadPourali** [comment]
Thank you for reporting this issue.
